name: "nightly"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  Spec:
    uses: "fvoges/cat-github-actions/.github/workflows/module_ci.yml@main"
    secrets: "inherit"

  # Acceptance:
  #   needs: Spec
  #   uses: "fvoges/cat-github-actions/.github/workflows/module_acceptance.yml@main"
  #   secrets: "inherit"
    
