---
name: "Release Prep"

on:
  # schedule:
  #   - cron: '0 3 * * 6'
  workflow_dispatch:
    inputs:
      version:
        description: "Module version to be released. Must be a valid semver string. (1.2.3)"
        required: true

jobs:
  release_prep:
    uses: "fvoges/cat-github-actions/.github/workflows/module_release_prep.yml@main"
    with:
      version: "${{ github.event.inputs.version }}"
    secrets: "inherit"
  
